name: Shuttle Deploy

on:
  push:
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy-action
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          secrets: |
            TELOXIDE_TOKEN = '${{ secrets.TELOXIDE_TOKEN }}'
